name: Tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, 'feature/initial-project-checkin' ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  STM32_TOOLCHAIN_PATH: /tmp/gcc-arm-none-eabi-10-2020-q4-major

jobs:
  test-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install pre-reqs
      working-directory: Examples/simple-example
      run: sudo apt-get install python3-pytest

    - name: Fetch toolchain for reuse
      run: |
        cd /tmp
        wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -O toolchain.tar.bz2
        tar xf toolchain.tar.bz2

    - name: Simple example
      run: pytest-3 tests
