name: Tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, 'feature/initial-project-checkin' ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Configure examples/blinky-example
      working-directory: Examples/blinky-example
      run: |
        which cmake
        echo hello world
        mkdir build
        cd build
        which cmake
        cmake ..

    - name: Build examples/blinky-example
      working-directory: examples/blinky-example/build
      shell: bash
      run: camke --build .
